#!/bin/bash

FILE=~/Downloads/Work/leagueChamps.csv

usage() {
	echo "$0 <command> [<args>]
	echo "Commands: "
	echo "list		list all types"
	echo "num		list out all classes"
}


list() {
	
	cat $FILE | cut -d "," -f3 | sort | uniq | grep -v Class
}

