#!/bin/bash

FILE=~/Downloads/leagueapp/leagueChamps.csv

usage() {
	echo "$@ <command> [<args>]"
	echo "Commands: "
	echo "list		list all types"
	echo "num		list out all classes"
}


list() {
	
	cat $FILE | cut -d "," -f3 | sort | uniq | grep -v Class
}

class() {
	cat $FILE | cut -d, -f3 | grep "$1" | sort | uniq -c
}

"$@"
